### PR TITLE
Pulled changes from Ash. Adjust handling data streams

### PR DESCRIPTION
**Pull request by jnackmclain**
I won't lie to you, I'm not super versed in this, but im going to be PR'ing ash's changes since he deleted everything.
Once merged ill do the same for [nex-protocols-go](https://github.com/jnackmclain/nex-protocols-go)

Going to try and keep things clean and not a ton of changes in single pulls

Thanks

### CODE REVIEW

**Comment by li1lypad** [comment]
This was aimed towards the older titles of Rock Band before Rock Band 3, but instead of it using a 4ByteString like 3, GDRB, TBRB, RB2 and RB1 use 2ByteStrings

**Comment by ihatecompvir** [comment]
@li1lypad Are these changes necessary for GoCentral to function or is this _just_ for legacy (pre-RB3) compatibility? My plan/idea was to put together a separate nex-go for use in older games (since it requires a lot of special tweaks like these, _especially_ nex-protocols-go) and keeping this one specifically for RB3. I'm not opposed to merging if necessary just want to clarify before doing so

**Comment by li1lypad** [comment]
@ihatecompvir These changes are only are only necessary for GoCentral if you're creating for e.g. a Green Day: Rock Band instance!

**Comment by DaniElectra** [comment]
I'm curious about the `ReadUInt24LE`. Does this actually exist in Quazal, or is it some sort of helper that doesn't represent a real Quazal data type?

**Comment by li1lypad** [comment]
> I'm curious about the `ReadUInt24LE`. Does this actually exist in Quazal, or is it some sort of helper that doesn't represent a real Quazal data type?

I don't think it actually does exist in Quazal, but I created it to try get matchmaking to work in Green Day: Rock Band and The Beatles: Rock Band. There was probably other ways of doing it but I went for an alternative route which worked.

**Pull request closed without merging**
